# Generated by Django 5.2.1 on 2025-05-20 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('discogs_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='music_album_title_ddf06b_idx'), models.Index(fields=['artist'], name='music_album_artist_6aded5_idx'), models.Index(fields=['release_date'], name='music_album_release_5ffcba_idx'), models.Index(fields=['discogs_id'], name='music_album_discogs_2fe89c_idx')],
            },
        ),
    ]
