# Generated by Django 5.0.1 on 2025-04-14 02:17

import django.core.validators
import django.db.models.deletion
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[music.models.validate_genre_name])),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('cover_art_url', models.URLField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('spotify_embed_url', models.URLField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('discogs_id', models.CharField(max_length=255, unique=True)),
                ('discogs_url', models.URLField(blank=True, null=True)),
                ('discogs_master_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('genres', models.ManyToManyField(to='music.genre')),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'artist'], name='music_album_title_d574c3_idx')],
            },
        ),
    ]
