# Generated by Django 5.0.1 on 2025-04-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musicbrainz_id',
            new_name='discogs_id',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='musicbrainz_id',
            new_name='discogs_id',
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_master_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='single',
            name='discogs_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
