# Generated by Django 5.2 on 2025-05-20 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_created_at_album_genres_album_styles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
