# Generated by Django 5.2 on 2025-05-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_review_genres_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='credits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='main_release_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='master_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='thumb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['master_id'], name='music_album_master__f1574f_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['year'], name='music_album_year_86c41a_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['label'], name='music_album_label_e86f35_idx'),
        ),
    ]
