# Generated by Django 5.2 on 2025-05-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_country_album_credits_album_format_album_label_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='album',
            name='music_album_master__f1574f_idx',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='music_album_year_86c41a_idx',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='music_album_label_e86f35_idx',
        ),
        migrations.RemoveField(
            model_name='album',
            name='country',
        ),
        migrations.RemoveField(
            model_name='album',
            name='format',
        ),
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.RemoveField(
            model_name='album',
            name='main_release_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='master_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='album',
            name='thumb_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='videos',
        ),
    ]
