# Generated by Django 5.2.2 on 2025-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_genre_style_remove_album_genres_remove_album_styles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='styles',
        ),
        migrations.RemoveField(
            model_name='review',
            name='genres',
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_genres',
            field=models.JSONField(blank=True, default=list, help_text='Original genres from Discogs'),
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_styles',
            field=models.JSONField(blank=True, default=list, help_text='Original styles from Discogs'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_genres',
            field=models.ManyToManyField(blank=True, help_text='User-selected genres for this album', related_name='reviews', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('POP', 'Pop'), ('HIP_HOP', 'Hip-Hop'), ('ROCK', 'Rock'), ('LATIN', 'Latin'), ('COUNTRY', 'Country'), ('ELECTRONIC', 'Electronic'), ('JAZZ', 'Jazz'), ('REGGAE', 'Reggae'), ('GOSPEL', 'Gospel'), ('CLASSICAL', 'Classical'), ('FUNK', 'Funk'), ('FOLK', 'Folk'), ('SOUNDTRACK', 'Soundtrack'), ('WORLD', 'World')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
