# Generated by Django 5.2.2 on 2025-06-08 23:13

from django.db import migrations


def create_initial_genres(apps, schema_editor):
    """Create the predefined genres"""
    Genre = apps.get_model('music', 'Genre')
    
    predefined_genres = [
        'Pop', 'Hip-Hop', 'Rock', 'Latin', 'Country', 'Electronic', 
        'Jazz', 'Reggae', 'Gospel', 'Classical', 'Funk', 'Folk', 
        'Soundtrack', 'World'
    ]
    
    for genre_name in predefined_genres:
        Genre.objects.get_or_create(name=genre_name)


def reverse_create_initial_genres(apps, schema_editor):
    """Remove the predefined genres (for migration rollback)"""
    Genre = apps.get_model('music', 'Genre')
    
    predefined_genres = [
        'Pop', 'Hip-Hop', 'Rock', 'Latin', 'Country', 'Electronic', 
        'Jazz', 'Reggae', 'Gospel', 'Classical', 'Funk', 'Folk', 
        'Soundtrack', 'World'
    ]
    
    Genre.objects.filter(name__in=predefined_genres).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_album_styles_remove_review_genres_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_genres, reverse_create_initial_genres),
    ]
