# Generated by Django 5.1.4 on 2025-06-09 05:59

from django.db import migrations
import re


def clean_artist_names(apps, schema_editor):
    """Clean up artist names by removing Discogs disambiguation numbers like (2), (3), etc."""
    Album = apps.get_model('music', 'Album')
    
    for album in Album.objects.all():
        if album.artist and re.search(r'\s*\(\d+\)$', album.artist):
            # Remove disambiguation numbers: (2), (3), (10), etc.
            clean_name = re.sub(r'\s*\(\d+\)$', '', album.artist).strip()
            if clean_name:  # Make sure we don't end up with an empty string
                print(f"Cleaning artist name: '{album.artist}' -> '{clean_name}'")
                album.artist = clean_name
                album.save()


def reverse_clean_artist_names(apps, schema_editor):
    """Reverse migration - this can't really be undone since we don't know the original numbers"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20250608_1813'),
    ]

    operations = [
        migrations.RunPython(clean_artist_names, reverse_clean_artist_names),
    ]
