# Generated by Django 5.2.2 on 2025-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_clean_artist_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this review to profile (max 4)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
