# Generated by Django 5.2.2 on 2025-06-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_add_comment_to_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activities'},
        ),
    ]
