# Generated by Django 5.2.2 on 2025-06-13 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['target_user', '-created_at'], name='music_activ_target__e886fd_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'activity_type', '-created_at'], name='music_activ_user_id_f83c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['target_user', 'activity_type', '-created_at'], name='music_activ_target__f15d25_idx'),
        ),
    ]
