# Generated by Django 5.2.3 on 2025-06-24 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_add_activity_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='music.list')),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='list',
            name='albums',
            field=models.ManyToManyField(related_name='lists', through='music.ListItem', to='music.album'),
        ),
        migrations.CreateModel(
            name='ListLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'order'], name='music_listi_list_id_47ad14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'album')},
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', '-updated_at'], name='music_list_user_id_f6706f_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['is_public', '-updated_at'], name='music_list_is_publ_cabb37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listlike',
            unique_together={('user', 'list')},
        ),
    ]
