# Generated by Django 5.2.3 on 2025-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_list_listitem_list_albums_listlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this review to profile (max 2)'),
        ),
    ]
