# Generated by Django 5.2.6 on 2025-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_add_review_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="music_review_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="music_review_album_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="reviewlike",
            name="music_reviewlike_review_created_idx",
        ),
        migrations.AddField(
            model_name="album",
            name="artist_photo_url",
            field=models.URLField(
                blank=True,
                help_text="URL to artist photo from external API",
                max_length=500,
                null=True,
            ),
        ),
    ]
