# Generated by Django 5.2.3 on 2025-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_location_user_name'),
        ('music', '0017_add_favorite_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, help_text='Favorite albums (max 5)', related_name='favorited_by', to='music.album'),
        ),
    ]
