# Generated by Django 5.2.3 on 2025-07-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_favorite_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified checkmark for trusted users'),
        ),
    ]
