# Generated by Django 5.2.3 on 2025-07-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_use_simple_cloudinary_for_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ] 