# Generated by Django 5.2.1 on 2025-05-20 05:15

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField(blank=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Country', 'Country'), ('Jazz', 'Jazz'), ('Gospel', 'Gospel'), ('Funk', 'Funk'), ('Soundtrack', 'Soundtrack'), ('Hip-hop', 'Hip-hop'), ('Latin', 'Latin'), ('Electronic', 'Electronic'), ('Reggae', 'Reggae'), ('Classical', 'Classical'), ('Folk', 'Folk'), ('World', 'World')], max_length=20), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx'), models.Index(fields=['album', 'created_at'], name='reviews_rev_album_i_737b4d_idx')],
            },
        ),
    ]
