# Generated by Django 5.0.1 on 2025-04-11 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('single', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.single')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx'), models.Index(fields=['album', 'created_at'], name='reviews_rev_album_i_737b4d_idx'), models.Index(fields=['single', 'created_at'], name='reviews_rev_single__e06810_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('album__isnull', False), ('single__isnull', True)), models.Q(('album__isnull', True), ('single__isnull', False)), _connector='OR'), name='review_either_album_or_single'),
        ),
    ]
